name: commune_app
description: A commune Flutter App project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts
vars:
  clean: fvm flutter clean
  get: fvm flutter pub get
  runner: fvm flutter pub run build_runner
  package_runner: fvm flutter packages pub run build_runner

scripts:
  build_runner_compile: $runner build --delete-conflicting-outputs
  build_runner_watch: $runner watch --delete-conflicting-outputs
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
  package_build: $package_runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.2
  flutter_mobx: ^2.0.6+1
  # flutter_screenutil: ^5.0.0+2
  mobx: ^2.0.7+2
  dart_jsonwebtoken: ^2.4.1

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  elastic_client: ^0.3.11
  json_serializable: ^6.2.0
  # connectivity: ^3.0.3
  # rxdart: ^0.26.0
  cryptography: ^2.0.5
  flutter_gallery_assets: ^1.0.2

  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  # intl_utils: ^2.1.0

  hive: ^2.2.0
  hive_flutter: ^1.1.0

  cached_network_image: ^3.2.1

  animations: ^2.0.2
  layout: ^1.0.2
  # loadmore: ^2.0.1
  flutter_webrtc: ^0.8.6
  device_info_plus: ^3.2.3
  socket_io_client: ^1.0.2
  bottom_navy_bar: ^6.0.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  # fluttertoast: ^7.1.8
  # multi_image_picker: ^4.8.0
  pull_to_refresh: ^2.0.0

  kakao_flutter_sdk: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  # Allows you to easily use any of the 977 fonts
  google_fonts: ^2.3.2


# dependency_overrides:
  # intl: ^0.17.0
  # analyzer: ^0.40.6
  # dart_style: '>=1.3.13 <=1.3.13'
  # dart_style: ^2.0.0
  # build_resolvers: '1.3.10'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0 # .10
  modular_codegen: ^3.0.4 # 2
  modular_test: ^2.0.0 # ^1.0.1+1
  mobx_codegen: ^2.0.2
  retrofit_generator: ^3.0.1 # ^2.0.1
  # chopper2_generator: ^3.0.6
  # built_value_generator: ^7.1.0
  hive_generator:
  build_runner: ^2.0.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true    # Add this line
  assets:
    - assets/data/
    - assets/images/
    - assets/icons/
    - assets/user.png
    - assets/cardimage.jpg
    - assets/keys/
    - packages/flutter_gallery_assets/reply/avatars/avatar_express.png
    - packages/flutter_gallery_assets/reply/icons/twotone_add_circle_outline.png
    - packages/flutter_gallery_assets/reply/icons/twotone_delete.png
    - packages/flutter_gallery_assets/reply/icons/twotone_drafts.png
    - packages/flutter_gallery_assets/reply/icons/twotone_error.png
    - packages/flutter_gallery_assets/reply/icons/twotone_folder.png
    - packages/flutter_gallery_assets/reply/icons/twotone_forward.png
    - packages/flutter_gallery_assets/reply/icons/twotone_inbox.png
    - packages/flutter_gallery_assets/reply/icons/twotone_send.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star_on_background.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star.png
    - packages/flutter_gallery_assets/reply/icons/twotone_stars.png
    - packages/flutter_gallery_assets/reply/reply_logo.png
    - packages/flutter_gallery_assets/reply/avatars/avatar_0.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_1.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_2.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_3.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_5.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_6.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_7.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_8.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_9.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_10.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Times
      fonts:
        - asset: assets/fonts/times_news_roman/Times New Roman 400.ttf
          weight: 400
        - asset: assets/fonts/times_news_roman/Times New Roman Gras 700.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/AvenirNextLTPro-Regular.otf
          weight: 400
        - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
          weight: 500
        - asset: assets/fonts/avenir/AvenirNextLTPro-Demi.otf
          weight: 600
        - asset: assets/fonts/avenir/avenir-next-lt-pro-bold.otf
          weight: 700
    - family: League
      fonts:
        - asset: assets/fonts/league_spartan/LeagueSpartan-Bold.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
